# Generated by Django 4.1.7 on 2023-02-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_rename_image_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
