# Generated by Django 4.1.7 on 2023-03-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
