# Generated by Django 4.1.7 on 2023-03-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
